// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID        string     `json:"id"`
	PostID    string     `json:"postID"`
	ParentID  *string    `json:"parentID,omitempty"`
	Text      string     `json:"text"`
	Replies   []*Comment `json:"replies"`
	CreatedAt string     `json:"createdAt"`
}

type Mutation struct {
}

type Post struct {
	ID              string     `json:"id"`
	Text            string     `json:"text"`
	CommentsEnabled bool       `json:"commentsEnabled"`
	CreatedAt       string     `json:"createdAt"`
	Comments        []*Comment `json:"comments"`
}

type Query struct {
}

type Subscription struct {
}
